app:
  eureka:
    username: nsliot
    password: Iotbrane2023
endpoint:
  cu: nsl-iot-changeunit
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.username}:${app.eureka.password}@localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
      

